server:
  port: 8888
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: true
        secure: false

spring:
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  security:
    loginType: JSON

